version: "3"

services:
  mysql-local:
    platform: linux/x86_64
    image: mysql:5.7.35
    container_name: mysql-local
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
