env:
  log:
    level: debug
    path: /Users/michael_kao/Documents/github/ql31j45k3/coding_style/go/layout_2/logs/demo_2_log
  debug: true
  server:
    port: 8080

db:
  gorm:
    logMode: Info
  master:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    name: demo_2

mongo:
  timeout: 300
  hosts:
    - "127.0.0.1:27017"
  authMechanism: "Direct"
  username:
  password:
  replicaSet:
  pool:
    debug: false
    minSize: 2
    maxSize: 25
    maxConnIdleTime: 300

redis:
  hosts:
    - "127.0.0.1:6371"
    - "127.0.0.1:6372"
    - "127.0.0.1:6373"
    - "127.0.0.1:6374"
    - "127.0.0.1:6375"
    - "127.0.0.1:6376"
  password:
  poolSize: 1000
